version: "3.3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "traefik.docker.network=proxy"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "proxy"

  nginx:
    image: "nginx:1.21-alpine"
    container_name: "nginx"
    depends_on:
      - "php"
    volumes:
      - "web_app:/var/www/html:ro"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "logs-nginx:/var/log/nginx"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.docker.network=proxy"
    networks:
      - "proxy"
      - "internal"

  php:
    build: "./fpm"
    image: "php:8.0-fpm-alpine"
    container_name: "php"
    volumes:
      - "web_app:/var/www/html:ro"
    labels:
      - "traefik.enable=false"
    networks:
      - "internal"

volumes:
  web_app:
    driver: "local"
    driver_opts:
      o: "bind"
      type: "none"
      device: "./src"
  logs-php:
  logs-nginx:

networks:
  proxy:
    external: true
    name: "proxy"
  internal:
    name: "internal"

